# TODO: markdownlint, yamllint


- name: markdownlint-cli
  uses: nosborn/github-action-markdown-cli@v3.3.0
  with:
    files: .
    config_file: .markdownlint.yaml
    dot: true
    ignore_files: examples/ignore/*
    ignore_path: examples/.markdownlintignore
    rules: examples/rules/custom.js
